name: Github Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [master, main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.*
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "chore: Update ${filename}"
          base: activity, community, repositories, metadata
          base_skip: header
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          config_order: introduction, base.activity+community, base.repositories, lines, wakatime, topics, achievements
