name: Github Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */8 * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: labels
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          
          
